"""New Migration

Revision ID: 97b8eb651c4d
Revises: 9b5e532e6654
Create Date: 2021-08-06 02:47:48.611263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b8eb651c4d'
down_revision = '9b5e532e6654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
