"""New Migration

Revision ID: 9b5e532e6654
Revises: e4acc5e0a7c7
Create Date: 2021-08-06 02:29:11.839937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5e532e6654'
down_revision = 'e4acc5e0a7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
